### ISSUE TITLE
Error after server side disconnect

### ISSUE THREAD

**Issue by briely** [rtc-io/rtc-signaller#30]
If the server disconnects and rtc-signaller attempts to automatically reconnect, the first message sent after reconnect triggers a disconnect event. This is using rtc-switchboard-messenger of course.

So I don't have a controlled test case yet, but I'm fairly sure this is something to do with reusing the pull-pushable output queue between sockets. I assume this is the case because signaller.close() before attempting to connect() fixes the problem.

**Comment by vkosh** [comment]
I've recently run into this issue. And signaller.close() in "disconnected" event handler fixes it indeed.
