### ISSUE TITLE
license should be a valid SPDX license expression

### ISSUE THREAD

**Issue by thisconnect** [rtc-io/rtc-signaller#36]
```bash
npm i
npm WARN package.json rtc-signaller@6.2.1 license should be a valid SPDX license expression
```

https://docs.npmjs.com/files/package.json#license

https://spdx.org/licenses/

**Comment by silviapfeiffer** [comment]
Sounds good! Can you add your name to the CLA at https://github.com/rtc-io/CLA/blob/master/CLA.md ? Then all your commits can be merged easily. Thanks.
