### ISSUE TITLE
Signaller sends announce message with "agent:unknown" ALWAYS while on Chrome

### ISSUE THREAD

**Issue by magestican** [rtc-io/rtc-signaller#39]

**Comment by nathanoehlman** [comment]
Strange - I'll take a look at it.

**Comment by magestican** [comment]
I am using rtc-signaller-socket.io but that uses the code in here, so thats why I am publishing the error here. thanks for taking a look.

**Comment by nathanoehlman** [comment]
It's actually just an issue inside `rtc-signaller-socker.io` - `rtc-signal` expects each signaller implementation to provide it's own agent string (ie. `rtc-signaller` does it here https://github.com/rtc-io/rtc-signaller/blob/master/index.js#L245), but `rtc-signaller-socket.io` was missing that. 

I've added it in, but unfortunately I don't have NPM publishing permissions for that package at the moment. Once I do, I'll publish a new `rtc-signaller-socket.io` package.
